### Sing in in the server | Get token
POST http://localhost:3017/api/v1/auth/login
Content-Type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM4Njk0MzQ2LCJleHAiOjE3MzkyOTkxNDZ9.H6dvUaYPlUSdpKIyX0a89cnql8duoBFWLxI9zdwLr90

{
  "username": "maya",
  "password": "dmaya78984%P"
}
### Dynamic
PUT http://localhost:3017/api/v1/system-settings/1
Content-Type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzM5MjA2NDY0LCJleHAiOjE3Mzk4MTEyNjR9.wNLeX0OdB2S1slGrKC4JHTQ4poljE-cs1dwMCJXT7R4

{
  "warehouse": ""
}

### GET ALL
POST http://localhost:3017/api/v1/functions/test
Content-Type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzM5NjYwNzM0LCJleHAiOjE3NDAyNjU1MzR9.FEcLT8CyENusE1qgDDgaklWOPs_sgkaTFDK-gi43aVE



